// Generated by vite-plugin-use-main - Do not edit manually!

// Provides type definitions for the API exposed via contextBridge ('mainApi')
// Automatically generated based on "use main" functions.

export interface MainApi {
  getOsInfo(detailLevel: number): Promise<{ platform: string; arch: string; hostname?: string }>;
  addNumbers(a: number, b: number): Promise<number>;
  riskyOperation(shouldFail: boolean): Promise<string>;
  testMainFunction(): Promise<string>;
  componentTestFunction(message: string): Promise<string>;
}

// Only declare these types in the appropriate environment
// This provides better compatibility with web and Electron environments
declare global {
  // Use conditional typing to avoid polluting the global namespace unnecessarily
  interface Window {
    mainApi?: MainApi;
  }
}
