// Generated by vite-plugin-use-electron
export interface MainApi {}

// Only declare these types in the appropriate environment
// This provides better compatibility with web and Electron environments
declare global {
  // Use conditional typing to avoid polluting the global namespace unnecessarily
  interface Window {
    mainApi?: MainApi;
  }
}
